// Lyco.toml — cargo 风格清单: 解析 / xmake.lua 生成 / add / remove / build / run
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

pub const MANIFEST: &str = "Lyco.toml";
const MIRROR: &str = "https://github.com/lilyco-42/xmake-mirror.git";

// ── 已知依赖注册表: 傻瓜式, 自动补 Windows 系统库 ──────────────
fn known_syslinks(name: &str) -> Option<&'static [&'static str]> {
    match name {
        "webview-capi" | "webview-mini" | "webview" => {
            Some(&["user32", "shell32", "ole32", "oleaut32", "shlwapi", "version"])
        }
        "webui" => Some(&["ws2_32", "user32", "gdi32", "shell32", "ole32"]),
        _ => None,
    }
}

/// 构建后需拷到 exe 旁边的运行时 DLL
fn known_dll(name: &str) -> Option<&'static str> {
    match name {
        "webview-capi" => Some("webview.dll"),
        _ => None,
    }
}

#[derive(serde::Deserialize, Default)]
pub struct Manifest {
    #[serde(default)]
    pub package: Pkg,
    #[serde(default)]
    pub dependencies: BTreeMap<String, toml::Value>,
}

#[derive(serde::Deserialize, Default)]
pub struct Pkg {
    pub name: Option<String>,
    pub version: Option<String>,
}

fn dep_version(v: &toml::Value) -> String {
    match v {
        toml::Value::String(s) => s.clone(),
        toml::Value::Table(t) => {
            t.get("version").and_then(|x| x.as_str()).unwrap_or("*").to_string()
        }
        _ => "*".into(),
    }
}

fn sample_manifest() -> String {
    format!(
        "未找到 {MANIFEST}。最小示例:\n\n\
         [package]\nname = \"app\"\nversion = \"0.1.0\"\n\n\
         [dependencies]\nwebview-capi = \"*\"\n\n\
         或 lyco new <name> c 一键生成。"
    )
}

impl Manifest {
    pub fn load() -> Result<Manifest, String> {
        if !Path::new(MANIFEST).exists() {
            return Err(sample_manifest());
        }
        let s = fs::read_to_string(MANIFEST).map_err(|e| e.to_string())?;
        toml::from_str(&s).map_err(|e| format!("{MANIFEST} 解析失败: {e}"))
    }

    pub fn project_name(&self) -> String {
        self.package.name.clone().unwrap_or_else(|| {
            std::env::current_dir()
                .ok()
                .and_then(|p| p.file_name().map(|n| n.to_string_lossy().to_string()))
                .unwrap_or_else(|| "app".into())
        })
    }
}

// ── 源文件探测 ──────────────────────────────────────────────
fn detect_src_pattern() -> &'static str {
    let src = Path::new("src");
    if !src.exists() {
        return "src/**.c";
    }
    let has = |ext: &str| {
        fs::read_dir(src).map(|rd| {
            rd.filter_map(|e| e.ok())
                .any(|e| e.path().extension().map(|x| x == ext).unwrap_or(false))
        }).unwrap_or(false)
    };
    if has("cpp") || has("cxx") || has("cc") { "src/**.cpp" } else { "src/**.c" }
}

// ── 生成 xmake.lua (构建产物, 勿手编) ────────────────────────
pub fn gen_xmake_lua(m: &Manifest) -> Result<(), String> {
    let name = m.project_name();
    let mut s = String::from("-- generated by lyco from Lyco.toml, do not edit\n");
    s.push_str("add_rules(\"mode.debug\", \"mode.release\")\n");
    s.push_str(&format!("add_repositories(\"lyco-mirror {MIRROR}\")\n\n"));

    let mut pkgs: Vec<String> = Vec::new();
    for (d, v) in &m.dependencies {
        let ver = dep_version(v);
        // xmake 版本约束语法: add_requires("zlib >=1.2"), "*" 只写包名
        let req = if ver == "*" || ver.is_empty() { d.clone() } else { format!("{d} >={ver}") };
        s.push_str(&format!("add_requires(\"{req}\")\n"));
        pkgs.push(d.clone());
    }

    s.push_str(&format!("\ntarget(\"{name}\")\n    set_kind(\"binary\")\n"));
    s.push_str(&format!("    add_files(\"{}\")\n", detect_src_pattern()));
    s.push_str("    add_includedirs(\".\", \"src\")\n");
    if !pkgs.is_empty() {
        s.push_str(&format!("    add_packages({})\n", pkgs.iter().map(|p| format!("\"{p}\"")).collect::<Vec<_>>().join(", ")));
    }
    let syslinks: Vec<&str> = m.dependencies.keys()
        .filter_map(|d| known_syslinks(d))
        .flat_map(|sl| sl.iter().copied())
        .collect();
    if !syslinks.is_empty() {
        let uniq: Vec<&str> = {
            let mut seen = Vec::new();
            for s2 in syslinks { if !seen.contains(&s2) { seen.push(s2); } }
            seen
        };
        s.push_str("    if is_plat(\"windows\") then\n");
        s.push_str(&format!(
            "        add_syslinks({})\n",
            uniq.iter().map(|l| format!("\"{l}\"")).collect::<Vec<_>>().join(", ")
        ));
        s.push_str("    end\n");
    }
    s.push_str("    if is_mode(\"release\") then set_optimize(\"smallest\") end\n");
    // 运行时 DLL 自动跟随 exe (mingw 不拷贝包的 bin, 这里兜底)
    for d in m.dependencies.keys() {
        if let Some(dll) = known_dll(d) {
            s.push_str(&format!(
                "    after_build(function (target)\n        local pkg = target:pkg(\"{d}\")\n        if pkg then\n            local dll = path.join(pkg:installdir(), \"bin\", \"{dll}\")\n            if os.isfile(dll) then os.cp(dll, target:targetdir()) end\n        end\n    end)\n"
            ));
        }
    }
    s.push_str("target_end()\n");
    fs::write("xmake.lua", s).map_err(|e| e.to_string())
}

// ── build / run ─────────────────────────────────────────────
fn plat(x: &str) -> Result<String, String> {
    Ok(match x.to_lowercase().as_str() {
        "windows" | "win" | "msvc" => "windows",
        "mingw" | "mingw64" | "gnu" => "mingw",
        "linux" => "linux",
        "macos" | "mac" | "darwin" => "macosx",
        "android" => "android",
        "ios" => "iphoneos",
        "wasm" | "wasi" => "wasm",
        other => return Err(format!("未知平台: {other} (windows/mingw/linux/macos/android/ios/wasm)")),
    }.to_string())
}

// ── 平台/工具链自动探测 ─────────────────────────────────────
/// 找 MinGW-w64 工具链根目录 (含 bin/gcc.exe)。找不到返回 None。
fn find_mingw_sdk() -> Option<String> {
    // 1) PATH 里的 gcc 若位于 <root>/bin/gcc.exe, 直接取 root (覆盖非 shim 安装)
    if let Ok(out) = Command::new("where").arg("gcc").output() {
        if out.status.success() {
            let stdout = String::from_utf8_lossy(&out.stdout).into_owned();
            let first = stdout.lines().next().unwrap_or("").trim();
            let p = Path::new(first);
            if p.file_name().map(|f| f == "gcc.exe").unwrap_or(false) {
                if let (Some(bin), Some(root)) = (p.parent(), p.parent().and_then(Path::parent)) {
                    if bin.file_name().map(|f| f == "bin").unwrap_or(false)
                        && root.join("bin").join("gcc.exe").exists() {
                        return Some(root.to_string_lossy().into_owned());
                    }
                }
            }
        }
    }
    // 2) scoop 布局 (shims 里的 gcc 拿不到真实路径, 按约定目录探测)
    let candidates = [
        env::var("SCOOP").ok().map(|s| format!("{s}\\apps\\gcc\\current")),
        env::var("USERPROFILE").ok().map(|h| format!("{h}\\scoop\\apps\\gcc\\current")),
    ];
    for c in candidates.into_iter().flatten() {
        if Path::new(&c).join("bin").join("gcc.exe").exists() {
            return Some(c);
        }
    }
    None
}

pub fn build(release: bool, target_plat: Option<&str>) -> Result<(), String> {
    let m = Manifest::load()?;
    gen_xmake_lua(&m)?;
    println!("⚙ 已从 {MANIFEST} 生成 xmake.lua ({} 个依赖)", m.dependencies.len());
    let plat_arg = target_plat.map(plat).transpose()?;
    // Windows 宿主默认: 优先 MinGW (MSVC 常缺 Windows SDK), 用户 --target 强制指定则尊重
    let mut conf = Command::new("xmake");
    conf.args(["f", "-y", "-m", if release { "release" } else { "debug" }]);
    if let Some(p) = plat_arg.as_deref() {
        conf.args(["-p", p]);
        if p == "mingw" {
            if let Some(sdk) = find_mingw_sdk() {
                conf.arg(format!("--sdk={sdk}"));
            }
        }
    } else if cfg!(windows) {
        if let Some(sdk) = find_mingw_sdk() {
            println!("🔧 工具链: MinGW-w64 ({sdk})");
            conf.args(["-p", "mingw"]);
            conf.arg(format!("--sdk={sdk}")); // xmake 只认等号形式
        } else {
            println!("🔧 工具链: MSVC (未发现 MinGW, 需要 Visual Studio C++ 工具集)");
            conf.args(["-p", "windows"]);
        }
    }
    let st = conf.status().map_err(|_| "xmake 未安装 (scoop install xmake)")?;
    if !st.success() { return Err("xmake 配置失败 (缺平台 SDK? 见上方输出)".into()); }
    let st = Command::new("xmake").args(["-y"]).status()
        .map_err(|_| "xmake 未安装 (scoop install xmake)")?;
    if !st.success() { return Err("构建失败".into()); }
    Ok(())
}

pub fn run(release: bool, target_plat: Option<&str>) -> Result<(), String> {
    let m = Manifest::load()?;
    build(release, target_plat)?;
    println!("▶ 运行 {}...", m.project_name());
    let st = Command::new("xmake").arg("run").status().map_err(|e| e.to_string())?;
    if !st.success() { return Err("运行失败".into()); }
    Ok(())
}

// ── add / remove (toml_edit 保注释保格式, 与 cargo 同款) ─────
pub fn add(dep: &str) -> Result<(), String> {
    if !Path::new(MANIFEST).exists() { return Err(sample_manifest()); }
    let (name, ver) = match dep.split_once('@') {
        Some((n, v)) => (n.trim().to_string(), v.trim().to_string()),
        None => (dep.trim().to_string(), "*".to_string()),
    };
    let content = fs::read_to_string(MANIFEST).map_err(|e| e.to_string())?;
    let mut doc = content.parse::<toml_edit::DocumentMut>().map_err(|e| e.to_string())?;
    if doc.get("dependencies").is_none() {
        doc["dependencies"] = toml_edit::Item::Table(toml_edit::Table::new());
    }
    doc["dependencies"][&name] = toml_edit::value(ver);
    fs::write(MANIFEST, doc.to_string()).map_err(|e| e.to_string())?;
    match known_syslinks(&name) {
        Some(sl) => println!("✅ 已添加 {name} (自动镜像源 + 系统库 {})", sl.join(", ")),
        None => println!("✅ 已添加 {name}"),
    }
    Ok(())
}

pub fn remove(dep: &str) -> Result<(), String> {
    if !Path::new(MANIFEST).exists() { return Err(sample_manifest()); }
    let content = fs::read_to_string(MANIFEST).map_err(|e| e.to_string())?;
    let mut doc = content.parse::<toml_edit::DocumentMut>().map_err(|e| e.to_string())?;
    let removed = doc
        .get_mut("dependencies")
        .and_then(|i| i.as_table_mut())
        .and_then(|t| t.remove(dep))
        .is_some();
    if !removed { return Err(format!("{MANIFEST} 中没有依赖 {dep}")); }
    fs::write(MANIFEST, doc.to_string()).map_err(|e| e.to_string())?;
    println!("✅ 已移除 {dep}");
    Ok(())
}
