// Lyco.toml — cargo 风格清单: 解析 / xmake.lua 生成 / add / remove / build / run
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

pub const MANIFEST: &str = "Lyco.toml";
const MIRROR: &str = "https://github.com/lilyco-42/xmake-mirror.git";

// ── 已知依赖注册表: 傻瓜式, 自动补 Windows 系统库 ──────────────
fn known_syslinks(name: &str) -> Option<&'static [&'static str]> {
    match name {
        "webview-capi" | "webview-mini" | "webview" => {
            Some(&["user32", "shell32", "ole32", "oleaut32", "shlwapi", "version"])
        }
        "webui" => Some(&["ws2_32", "user32", "gdi32", "shell32", "ole32"]),
        _ => None,
    }
}

/// 构建后需拷到 exe 旁边的运行时 DLL
fn known_dll(name: &str) -> Option<&'static str> {
    match name {
        "webview-capi" => Some("webview.dll"),
        _ => None,
    }
}

// ── 注册表 (lyco search) ────────────────────────────────────
pub const REGISTRY: &[(&str, &str)] = &[
    ("webview-capi", "WebView2/WKWebView/WebKitGTK 极小 C API (预编译, lyco 维护)"),
    ("webview-mini", "webview/webview 单头文件极简封装"),
    ("webview",      "webview/webview 官方库"),
    ("webui",        "WebUI — 用任意浏览器做 GUI"),
];

pub fn search(q: &str) {
    let q = q.to_lowercase();
    let mut found = 0;
    for (n, d) in REGISTRY {
        if n.contains(&q) || d.to_lowercase().contains(&q) {
            println!("{n:<14} {d}");
            found += 1;
        }
    }
    if found == 0 {
        println!("(注册表无匹配 — 任意 xmake 包仍可用: lyco add <xmake包名>)");
    }
}

#[derive(serde::Deserialize, Default)]
pub struct Manifest {
    #[serde(default)]
    pub package: Pkg,
    #[serde(default)]
    pub dependencies: BTreeMap<String, toml::Value>,
}

#[derive(serde::Deserialize, Default)]
pub struct Pkg {
    pub name: Option<String>,
    pub version: Option<String>,
}

fn dep_version(v: &toml::Value) -> String {
    match v {
        toml::Value::String(s) => s.clone(),
        toml::Value::Table(t) => {
            t.get("version").and_then(|x| x.as_str()).unwrap_or("*").to_string()
        }
        _ => "*".into(),
    }
}

fn sample_manifest() -> String {
    format!(
        "未找到 {MANIFEST}。最小示例:\n\n\
         [package]\nname = \"app\"\nversion = \"0.1.0\"\n\n\
         [dependencies]\nwebview-capi = \"*\"\n\n\
         或 lyco new <name> c 一键生成。"
    )
}

impl Manifest {
    pub fn load() -> Result<Manifest, String> {
        if !Path::new(MANIFEST).exists() {
            return Err(sample_manifest());
        }
        let s = fs::read_to_string(MANIFEST).map_err(|e| e.to_string())?;
        toml::from_str(&s).map_err(|e| format!("{MANIFEST} 解析失败: {e}"))
    }

    pub fn project_name(&self) -> String {
        self.package.name.clone().unwrap_or_else(|| {
            std::env::current_dir()
                .ok()
                .and_then(|p| p.file_name().map(|n| n.to_string_lossy().to_string()))
                .unwrap_or_else(|| "app".into())
        })
    }
}

// ── 源文件探测 ──────────────────────────────────────────────
fn detect_src_pattern() -> &'static str {
    let src = Path::new("src");
    if !src.exists() {
        return "src/**.c";
    }
    let has = |ext: &str| {
        fs::read_dir(src).map(|rd| {
            rd.filter_map(|e| e.ok())
                .any(|e| e.path().extension().map(|x| x == ext).unwrap_or(false))
        }).unwrap_or(false)
    };
    if has("cpp") || has("cxx") || has("cc") { "src/**.cpp" } else { "src/**.c" }
}

// ── 生成 xmake.lua (构建产物, 勿手编) ────────────────────────
pub fn gen_xmake_lua(m: &Manifest) -> Result<(), String> {
    let name = m.project_name();
    let mut s = String::from("-- generated by lyco from Lyco.toml, do not edit\n");
    s.push_str("add_rules(\"mode.debug\", \"mode.release\")\n");
    s.push_str(&format!("add_repositories(\"lyco-mirror {MIRROR}\")\n\n"));

    let mut pkgs: Vec<String> = Vec::new();
    for (d, v) in &m.dependencies {
        let ver = dep_version(v);
        // xmake 版本约束语法: add_requires("zlib >=1.2"), "*" 只写包名
        let req = if ver == "*" || ver.is_empty() { d.clone() } else { format!("{d} >={ver}") };
        s.push_str(&format!("add_requires(\"{req}\")\n"));
        pkgs.push(d.clone());
    }

    // 依赖接线块 (主 target 与测试 target 共用)
    let syslinks: Vec<&str> = m.dependencies.keys()
        .filter_map(|d| known_syslinks(d))
        .flat_map(|sl| sl.iter().copied())
        .collect();
    let mut uniq: Vec<&str> = vec![];
    for s2 in &syslinks { if !uniq.contains(s2) { uniq.push(s2); } }
    let mut deps_block = String::new();
    if !pkgs.is_empty() {
        deps_block.push_str(&format!("    add_packages({})\n",
            pkgs.iter().map(|p| format!("\"{p}\"")).collect::<Vec<_>>().join(", ")));
    }
    if !uniq.is_empty() {
        deps_block.push_str("    if is_plat(\"windows\") then\n");
        deps_block.push_str(&format!("        add_syslinks({})\n",
            uniq.iter().map(|l| format!("\"{l}\"")).collect::<Vec<_>>().join(", ")));
        deps_block.push_str("    end\n");
    }
    // 运行时 DLL 自动跟随 exe (mingw 不拷贝包的 bin, 这里兜底)
    for d in m.dependencies.keys() {
        if let Some(dll) = known_dll(d) {
            deps_block.push_str(&format!(
                "    after_build(function (target)\n        local pkg = target:pkg(\"{d}\")\n        if pkg then\n            local dll = path.join(pkg:installdir(), \"bin\", \"{dll}\")\n            if os.isfile(dll) then os.cp(dll, target:targetdir()) end\n        end\n    end)\n"
            ));
        }
    }

    s.push_str(&format!("\ntarget(\"{name}\")\n    set_kind(\"binary\")\n"));
    s.push_str(&format!("    add_files(\"{}\")\n", detect_src_pattern()));
    s.push_str("    add_includedirs(\".\", \"src\")\n");
    s.push_str(&deps_block);
    s.push_str("    if is_mode(\"release\") then set_optimize(\"smallest\") end\ntarget_end()\n");

    // tests/*.c → 独立测试 target (lyco test 驱动, 不参与默认构建)
    if let Ok(rd) = fs::read_dir("tests") {
        for e in rd.filter_map(|e| e.ok()).collect::<Vec<_>>() {
            let p = e.path();
            if !matches!(p.extension().and_then(|x| x.to_str()), Some("c") | Some("cpp")) { continue; }
            let stem = p.file_stem().unwrap().to_string_lossy();
            let fname = p.file_name().unwrap().to_string_lossy();
            s.push_str(&format!(
                "\ntarget(\"test_{stem}\")\n    set_kind(\"binary\")\n    set_default(false)\n    add_files(\"tests/{fname}\")\n    add_includedirs(\".\", \"src\")\n"
            ));
            s.push_str(&deps_block);
            s.push_str("target_end()\n");
        }
    }
    fs::write("xmake.lua", s).map_err(|e| e.to_string())
}

// ── build / run ─────────────────────────────────────────────
fn plat(x: &str) -> Result<String, String> {
    Ok(match x.to_lowercase().as_str() {
        "windows" | "win" | "msvc" => "windows",
        "mingw" | "mingw64" | "gnu" => "mingw",
        "linux" => "linux",
        "macos" | "mac" | "darwin" => "macosx",
        "android" => "android",
        "ios" => "iphoneos",
        "wasm" | "wasi" => "wasm",
        other => return Err(format!("未知平台: {other} (windows/mingw/linux/macos/android/ios/wasm)")),
    }.to_string())
}

// ── 平台/工具链自动探测 ─────────────────────────────────────
/// 找 MinGW-w64 工具链根目录 (含 bin/gcc.exe)。找不到返回 None。
fn find_mingw_sdk() -> Option<String> {
    // 1) PATH 里的 gcc 若位于 <root>/bin/gcc.exe, 直接取 root (覆盖非 shim 安装)
    if let Ok(out) = Command::new("where").arg("gcc").output() {
        if out.status.success() {
            let stdout = String::from_utf8_lossy(&out.stdout).into_owned();
            let first = stdout.lines().next().unwrap_or("").trim();
            let p = Path::new(first);
            if p.file_name().map(|f| f == "gcc.exe").unwrap_or(false) {
                if let (Some(bin), Some(root)) = (p.parent(), p.parent().and_then(Path::parent)) {
                    if bin.file_name().map(|f| f == "bin").unwrap_or(false)
                        && root.join("bin").join("gcc.exe").exists() {
                        return Some(root.to_string_lossy().into_owned());
                    }
                }
            }
        }
    }
    // 2) scoop 布局 (shims 里的 gcc 拿不到真实路径, 按约定目录探测)
    let candidates = [
        env::var("SCOOP").ok().map(|s| format!("{s}\\apps\\gcc\\current")),
        env::var("USERPROFILE").ok().map(|h| format!("{h}\\scoop\\apps\\gcc\\current")),
    ];
    for c in candidates.into_iter().flatten() {
        if Path::new(&c).join("bin").join("gcc.exe").exists() {
            return Some(c);
        }
    }
    None
}

/// xmake 配置的平台/工具链参数 (build 与 check 共用)
fn platform_args(target_plat: Option<&str>) -> Result<Vec<String>, String> {
    let mut v: Vec<String> = vec![];
    let plat_arg = target_plat.map(plat).transpose()?;
    if let Some(p) = plat_arg.as_deref() {
        v.push("-p".into());
        v.push(p.into());
        if p == "mingw" {
            if let Some(sdk) = find_mingw_sdk() {
                v.push(format!("--sdk={sdk}")); // xmake 只认等号形式
            }
        }
    } else if cfg!(windows) {
        // Windows 宿主默认: 优先 MinGW (MSVC 常缺 Windows SDK)
        if let Some(sdk) = find_mingw_sdk() {
            println!("🔧 工具链: MinGW-w64 ({sdk})");
            v.push("-p".into());
            v.push("mingw".into());
            v.push(format!("--sdk={sdk}"));
        } else {
            println!("🔧 工具链: MSVC (未发现 MinGW, 需要 Visual Studio C++ 工具集)");
            v.push("-p".into());
            v.push("windows".into());
        }
    }
    Ok(v)
}

fn xmake_config(release: bool, target_plat: Option<&str>) -> Result<(), String> {
    let mut conf = Command::new("xmake");
    conf.args(["f", "-y", "-m", if release { "release" } else { "debug" }]);
    for a in platform_args(target_plat)? {
        conf.arg(a);
    }
    let st = conf.status().map_err(|_| "xmake 未安装 (scoop install xmake)")?;
    if !st.success() { return Err("xmake 配置失败 (缺平台 SDK? 见上方输出)".into()); }
    Ok(())
}

pub fn build(release: bool, target_plat: Option<&str>) -> Result<(), String> {
    let m = Manifest::load()?;
    gen_xmake_lua(&m)?;
    println!("⚙ 已从 {MANIFEST} 生成 xmake.lua ({} 个依赖)", m.dependencies.len());
    xmake_config(release, target_plat)?;
    let st = Command::new("xmake").args(["-y"]).status()
        .map_err(|_| "xmake 未安装 (scoop install xmake)")?;
    if !st.success() { return Err("构建失败".into()); }
    Ok(())
}

pub fn run(release: bool, target_plat: Option<&str>) -> Result<(), String> {
    let m = Manifest::load()?;
    build(release, target_plat)?;
    println!("▶ 运行 {}...", m.project_name());
    let st = Command::new("xmake").arg("run").status().map_err(|e| e.to_string())?;
    if !st.success() { return Err("运行失败".into()); }
    Ok(())
}

// ── add / remove (toml_edit 保注释保格式, 与 cargo 同款) ─────
pub fn add(dep: &str) -> Result<(), String> {
    if !Path::new(MANIFEST).exists() { return Err(sample_manifest()); }
    let (name, ver) = match dep.split_once('@') {
        Some((n, v)) => (n.trim().to_string(), v.trim().to_string()),
        None => (dep.trim().to_string(), "*".to_string()),
    };
    let content = fs::read_to_string(MANIFEST).map_err(|e| e.to_string())?;
    let mut doc = content.parse::<toml_edit::DocumentMut>().map_err(|e| e.to_string())?;
    if doc.get("dependencies").is_none() {
        doc["dependencies"] = toml_edit::Item::Table(toml_edit::Table::new());
    }
    doc["dependencies"][&name] = toml_edit::value(ver);
    fs::write(MANIFEST, doc.to_string()).map_err(|e| e.to_string())?;
    match known_syslinks(&name) {
        Some(sl) => println!("✅ 已添加 {name} (自动镜像源 + 系统库 {})", sl.join(", ")),
        None => println!("✅ 已添加 {name}"),
    }
    Ok(())
}

pub fn remove(dep: &str) -> Result<(), String> {
    if !Path::new(MANIFEST).exists() { return Err(sample_manifest()); }
    let content = fs::read_to_string(MANIFEST).map_err(|e| e.to_string())?;
    let mut doc = content.parse::<toml_edit::DocumentMut>().map_err(|e| e.to_string())?;
    let removed = doc
        .get_mut("dependencies")
        .and_then(|i| i.as_table_mut())
        .and_then(|t| t.remove(dep))
        .is_some();
    if !removed { return Err(format!("{MANIFEST} 中没有依赖 {dep}")); }
    fs::write(MANIFEST, doc.to_string()).map_err(|e| e.to_string())?;
    println!("✅ 已移除 {dep}");
    Ok(())
}

// ── check: 语法检查 (不产出目标文件) ────────────────────────
fn collect_includes(dir: &Path, depth: usize, out: &mut Vec<PathBuf>) {
    if depth > 5 { return; }
    let rd = match fs::read_dir(dir) { Ok(r) => r, Err(_) => return };
    for e in rd.filter_map(|e| e.ok()) {
        let p = e.path();
        if p.is_dir() {
            if p.file_name().map(|n| n == "include").unwrap_or(false) {
                out.push(p.clone());
            }
            collect_includes(&p, depth + 1, out);
        }
    }
}

fn collect_src(dir: &Path, out: &mut Vec<PathBuf>) {
    let rd = match fs::read_dir(dir) { Ok(r) => r, Err(_) => return };
    for e in rd.filter_map(|e| e.ok()) {
        let p = e.path();
        if p.is_dir() {
            collect_src(&p, out);
        } else if matches!(p.extension().and_then(|x| x.to_str()), Some("c") | Some("cpp")) {
            out.push(p);
        }
    }
}

pub fn check() -> Result<(), String> {
    let m = Manifest::load()?;
    gen_xmake_lua(&m)?;
    xmake_config(false, None)?; // 配置+装包, 使包 include 目录就绪

    let mut incs: Vec<PathBuf> = vec![PathBuf::from("."), PathBuf::from("src")];
    if let Ok(base) = env::var("LOCALAPPDATA") {
        collect_includes(&PathBuf::from(base).join(".xmake/packages"), 0, &mut incs);
    }
    let gcc = find_mingw_sdk().map(|s| format!("{s}\\bin\\gcc.exe"));
    let prog = match gcc {
        Some(g) if Path::new(&g).exists() => g,
        _ => return Err("check 需要编译器: scoop install gcc (或安装完整 MSVC)".into()),
    };

    let mut files: Vec<PathBuf> = vec![];
    collect_src(Path::new("src"), &mut files);
    if files.is_empty() { return Err("src/ 下没有源文件".into()); }

    let mut bad = 0;
    for f in &files {
        let mut c = Command::new(&prog);
        c.arg("-fsyntax-only");
        for i in &incs { c.arg(format!("-I{}", i.display())); }
        c.arg(f);
        let out = c.output();
        let ok = out.as_ref().map(|o| o.status.success()).unwrap_or(false);
        println!("{} {}", if ok { "✔" } else { "✘" }, f.display());
        if !ok {
            if let Ok(o) = out {
                let err = String::from_utf8_lossy(&o.stderr);
                for line in err.lines().take(6) { println!("    {line}"); }
            }
            bad += 1;
        }
    }
    if bad > 0 { return Err(format!("{bad} 个文件未通过语法检查")); }
    println!("✅ 语法检查通过 ({} 个文件)", files.len());
    Ok(())
}

// ── test: tests/*.c → 每个文件一个测试 target 并逐个运行 ────
pub fn test() -> Result<(), String> {
    let m = Manifest::load()?;
    build(false, None)?; // gen_xmake_lua 会为 tests/ 生成 test_* target

    let rd = fs::read_dir("tests").map_err(|_| "没有 tests/ 目录 (放 tests/xxx.c 后重试)".to_string())?;
    let mut ran = 0;
    let mut failed = 0;
    for e in rd.filter_map(|e| e.ok()) {
        let p = e.path();
        if !matches!(p.extension().and_then(|x| x.to_str()), Some("c") | Some("cpp")) { continue; }
        let stem = p.file_stem().unwrap().to_string_lossy().into_owned();
        println!("▶ 运行测试 {stem} ...");
        let st = Command::new("xmake").args(["run", &format!("test_{stem}")]).status();
        ran += 1;
        match st {
            Ok(s) if s.success() => println!("✔ {stem}"),
            _ => { println!("✘ {stem}"); failed += 1; }
        }
    }
    if ran == 0 { return Err("tests/ 下没有 .c/.cpp 测试文件".into()); }
    if failed > 0 { return Err(format!("{failed}/{ran} 个测试失败")); }
    println!("✅ {ran} 个测试全部通过");
    Ok(())
}

// ── install / uninstall: 构建并安装到 ~/.lyco/bin ───────────
fn find_built_exe(dir: &Path, name: &str) -> Option<PathBuf> {
    let rd = fs::read_dir(dir).ok()?;
    for e in rd.filter_map(|e| e.ok()) {
        let p = e.path();
        if p.is_dir() {
            if let Some(f) = find_built_exe(&p, name) { return Some(f); }
        } else if p.file_name().map(|n| n.to_string_lossy() == format!("{name}.exe")).unwrap_or(false) {
            return Some(p);
        }
    }
    None
}

pub fn install() -> Result<(), String> {
    build(true, None)?;
    let m = Manifest::load()?;
    let name = m.project_name();
    let exe = find_built_exe(Path::new("build"), &name)
        .ok_or("构建产物未找到 (build/**/<name>.exe)")?;
    let dest_dir = super::data_dir().join("bin");
    fs::create_dir_all(&dest_dir).map_err(|e| e.to_string())?;
    let dest = dest_dir.join(format!("{name}.exe"));
    fs::copy(&exe, &dest).map_err(|e| e.to_string())?;
    println!("✅ 已安装 {}", dest.display());
    println!("   提示: 把 {} 加入 PATH 后可全局调用", dest_dir.display());
    Ok(())
}

pub fn uninstall(name: Option<&str>) -> Result<(), String> {
    let n = match name {
        Some(n) => n.to_string(),
        None => Manifest::load()?.project_name(),
    };
    let p = super::data_dir().join("bin").join(format!("{n}.exe"));
    if p.exists() {
        fs::remove_file(&p).map_err(|e| e.to_string())?;
        println!("✅ 已卸载 {}", p.display());
    } else {
        println!("ℹ 未安装: {}", p.display());
    }
    Ok(())
}
